#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\NewsArea\Views\Home\ShowResources.cshtml"
    using MvcPluginMasterApp.Plugin1.DomainClasses;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/NewsArea/Views/Home/ShowResources.cshtml")]
    public partial class _Areas_NewsArea_Views_Home_ShowResources_cshtml : System.Web.Mvc.WebViewPage<News>
    {
        public _Areas_NewsArea_Views_Home_ShowResources_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\NewsArea\Views\Home\ShowResources.cshtml"
  
    ViewBag.Title = "Show Resources";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 6 "..\..\Areas\NewsArea\Views\Home\ShowResources.cshtml"
Write(Styles.Render("~/Plugin1/Content"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>");

            
            #line 8 "..\..\Areas\NewsArea\Views\Home\ShowResources.cshtml"
Write(ViewBag.Message);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <fieldset>\r\n        <legend>News Info (");

WriteLiteral("@Home_Index_cshtml.Title)</legend>\r\n        CurrentCulture: ");

            
            #line 14 "..\..\Areas\NewsArea\Views\Home\ShowResources.cshtml"
                   Write(System.Threading.Thread.CurrentThread.CurrentCulture.ToString());

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"display-label\"");

WriteLiteral(">");

            
            #line 15 "..\..\Areas\NewsArea\Views\Home\ShowResources.cshtml"
                              Write(MvcPluginMasterApp.Plugin1.Resources.Home_Index_cshtml.Title);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        <div");

WriteLiteral(" class=\"display-field\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 17 "..\..\Areas\NewsArea\Views\Home\ShowResources.cshtml"
       Write(Html.DisplayFor(model => model.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </fieldset>\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <fieldset>\r\n        <legend>News Info (");

WriteLiteral("@Html.DisplayForModel)</legend>\r\n");

WriteLiteral("        ");

            
            #line 25 "..\..\Areas\NewsArea\Views\Home\ShowResources.cshtml"
   Write(Html.DisplayForModel());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </fieldset>\r\n</div>\r\n\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 32 "..\..\Areas\NewsArea\Views\Home\ShowResources.cshtml"
Write(Scripts.Render("~/Plugin1/Scripts"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
